
name: Generate pinout images for all boards.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use latest Python 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pinout
        python -m pip install setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Python script
      working-directory: esp32_lpkit
      run: python pinout_diagram.py  # Replace with your actual script name
    
    - name: Upload generated pinouts
      uses: actions/upload-artifact@v4
      with:
        name: generated-image
        path: esp32_lpkit/diagram.svg
        retention-days: 30  # Keep artifact for 30 days

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')  # Only create release for tags
      uses: softprops/action-gh-release@v2
      with:
        files: |
          esp32_lpkit/diagram.svg
        name: Release ${{ github.ref_name }}
        body: |
          ## Generated Image Release
          
          This release contains the automatically generated image from the Python script.
          
          ### Changes
          - Generated diagram.svg from latest script version
          
        generate_release_notes: true
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
